version: '3.6'

services:
  redis:
     image: redis:2.8
     ports:
      - 6379:6379
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on: 
      - redis
